dbt_airflow:
  outputs:
    dev:
      dbname: data-challenge-dbt
      host: localhost
      pass: postgres
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev